"""add_trending_rankings_table

Revision ID: 0e2676090eed
Revises: 71fffd6203e2
Create Date: 2026-07-28 12:00:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0e2676090eed"
down_revision: str | Sequence[str] | None = "71fffd6203e2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "trending_rankings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tmdb_id", sa.String(length=20), nullable=False),
        sa.Column("media_type", sa.String(length=20), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("trending_window", sa.String(length=20), nullable=False),
        sa.Column("scraped_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tmdb_id", "media_type", "trending_window",
            name="uq_trending_tmdb_window",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("trending_rankings")
    # ### end Alembic commands ###
