"""initial_schema_unified

Revision ID: 71fffd6203e2
Revises:
Create Date: 2026-07-21 00:21:17.217449

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "71fffd6203e2"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "calendario",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("fecha", sa.Date(), nullable=False),
        sa.Column("hora", sa.Text(), nullable=False),
        sa.Column("competicion", sa.Text(), nullable=True),
        sa.Column("subtitulo_competicion", sa.Text(), nullable=True),
        sa.Column("categoria", sa.Text(), nullable=True),
        sa.Column("equipos", sa.Text(), nullable=False),
        sa.Column("imagen_evento", sa.Text(), nullable=True),
        sa.Column("canales", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("fecha", "hora", "equipos", name="uq_calendario_fecha_hora_equipos"),
    )
    op.create_table(
        "channel_mappings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("source_name", sa.Text(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_name"),
    )
    op.create_table(
        "channels",
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("provider_id", sa.String(length=50), nullable=True),
        sa.Column("nombre", sa.String(length=255), nullable=False),
        sa.Column("nombre_normalizado", sa.String(length=255), nullable=True),
        sa.Column("logo", sa.Text(), nullable=True),
        sa.Column("grupo", sa.String(length=255), nullable=True),
        sa.Column("grupo_normalizado", sa.String(length=255), nullable=True),
        sa.Column("country", sa.String(length=10), nullable=True),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("numero", sa.Integer(), nullable=True),
        sa.Column("tvg_id", sa.String(length=100), nullable=True),
        sa.Column("stream_url", sa.Text(), nullable=True),
        sa.Column("ultimo_chequeo", sa.DateTime(timezone=True), nullable=True),
        sa.Column("estado_stream", sa.String(length=50), nullable=True),
        sa.Column("tiempo_respuesta_ms", sa.Integer(), nullable=True),
        sa.Column("last_sync_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "config",
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("value", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "movies_metadata",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("runtime_minutes", sa.Integer(), nullable=True),
        sa.Column("tmdb_id", sa.String(length=20), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("original_title", sa.String(length=255), nullable=True),
        sa.Column("overview_es", sa.Text(), nullable=True),
        sa.Column("overview_en", sa.Text(), nullable=True),
        sa.Column("genres", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("vote_average", sa.Float(), nullable=True),
        sa.Column("vote_count", sa.Integer(), nullable=True),
        sa.Column("poster_path", sa.String(length=255), nullable=True),
        sa.Column("backdrop_path", sa.String(length=255), nullable=True),
        sa.Column("release_date", sa.Date(), nullable=True),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("tagline", sa.String(length=500), nullable=True),
        sa.Column("popularity", sa.Float(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("imdb_id", sa.String(length=20), nullable=True),
        sa.Column("tmdb_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("scraped_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tmdb_id"),
    )
    op.create_table(
        "replays",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("source_site", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("event_name", sa.Text(), nullable=True),
        sa.Column("event_type", sa.Text(), nullable=True),
        sa.Column("event_date", sa.Date(), nullable=True),
        sa.Column("post_url", sa.Text(), nullable=False),
        sa.Column("featured_image_url", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("video_sources", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("match_card", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "scraper_failures",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("provider_id", sa.String(length=50), nullable=True),
        sa.Column("series_key", sa.String(length=255), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("failed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=True),
        sa.Column("last_retry_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_failures_provider",
        "scraper_failures",
        ["provider_id"],
        unique=True,
        postgresql_where=sa.text("provider_id IS NOT NULL"),
    )
    op.create_index(
        "idx_failures_series",
        "scraper_failures",
        ["series_key"],
        unique=True,
        postgresql_where=sa.text("series_key IS NOT NULL"),
    )
    op.create_table(
        "series_metadata",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tmdb_id", sa.String(length=20), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("original_title", sa.String(length=255), nullable=True),
        sa.Column("overview_es", sa.Text(), nullable=True),
        sa.Column("overview_en", sa.Text(), nullable=True),
        sa.Column("genres", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("vote_average", sa.Float(), nullable=True),
        sa.Column("vote_count", sa.Integer(), nullable=True),
        sa.Column("poster_path", sa.String(length=255), nullable=True),
        sa.Column("backdrop_path", sa.String(length=255), nullable=True),
        sa.Column("release_date", sa.Date(), nullable=True),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("tagline", sa.String(length=500), nullable=True),
        sa.Column("popularity", sa.Float(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("imdb_id", sa.String(length=20), nullable=True),
        sa.Column("tmdb_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("scraped_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tmdb_id"),
    )
    op.create_table(
        "sync_metadata",
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("ultima_actualizacion", postgresql.TIMESTAMP(), nullable=True),
        sa.Column("total_canales", sa.Integer(), server_default="0", nullable=True),
        sa.Column("total_movies", sa.Integer(), server_default="0", nullable=True),
        sa.Column("total_series", sa.Integer(), server_default="0", nullable=True),
        sa.Column("m3u_template_path", sa.Text(), nullable=True),
        sa.Column("m3u_template_filename", sa.Text(), nullable=True),
        sa.Column("m3u_size_mb", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("channels_con_logo", sa.Integer(), server_default="0", nullable=True),
        sa.Column("channels_sin_logo", sa.Integer(), server_default="0", nullable=True),
        sa.Column("movies_con_logo", sa.Integer(), server_default="0", nullable=True),
        sa.Column("movies_sin_logo", sa.Integer(), server_default="0", nullable=True),
        sa.Column("series_con_logo", sa.Integer(), server_default="0", nullable=True),
        sa.Column("series_sin_logo", sa.Integer(), server_default="0", nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(), nullable=True),
        sa.Column("updated_at", postgresql.TIMESTAMP(), nullable=True),
        sa.Column("channels_generated_at", postgresql.TIMESTAMP(), nullable=True),
        sa.Column("channels_json_size_mb", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("movies_generated_at", postgresql.TIMESTAMP(), nullable=True),
        sa.Column("movies_json_size_mb", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("series_generated_at", postgresql.TIMESTAMP(), nullable=True),
        sa.Column("series_json_size_mb", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("max_connections", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("role", sa.String(length=20), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "active_sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("device_id", sa.String(length=64), nullable=False),
        sa.Column("device_name", sa.String(length=100), nullable=True),
        sa.Column("device_type", sa.String(length=20), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.String(), nullable=True),
        sa.Column("last_activity", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "device_id"),
    )
    op.create_table(
        "channel_favorites",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("channel_provider_id", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "channel_provider_id"),
    )
    op.create_table(
        "channel_variants",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("mapping_id", sa.Integer(), nullable=False),
        sa.Column("channel_id", sa.String(length=50), nullable=True),
        sa.Column("quality", sa.Text(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["channel_id"], ["channels.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["mapping_id"], ["channel_mappings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "movies_catalog",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tmdb_id", sa.String(length=20), nullable=True),
        sa.Column("not_found", sa.Boolean(), server_default="false", nullable=True),
        sa.Column("retry_count", sa.Integer(), server_default="0", nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("last_sync_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("provider_id", sa.String(length=50), nullable=True),
        sa.Column("nombre_dedup_key", sa.Text(), nullable=True),
        sa.Column("canonical_key", sa.String(), nullable=True),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("countries", postgresql.ARRAY(sa.String(length=10)), nullable=True),
        sa.Column("group_normalizado", sa.Text(), nullable=True),
        sa.Column("logo", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["tmdb_id"], ["movies_metadata.tmdb_id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uq_movies_catalog_tmdb",
        "movies_catalog",
        ["tmdb_id"],
        unique=True,
        postgresql_where=sa.text("tmdb_id IS NOT NULL"),
    )
    op.create_table(
        "series_catalog",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("series_key", sa.Text(), nullable=False),
        sa.Column("canonical_key", sa.String(), nullable=True),
        sa.Column("provider_id", sa.String(length=50), nullable=True),
        sa.Column("tmdb_id", sa.String(length=20), nullable=True),
        sa.Column("nombre_dedup_key", sa.Text(), nullable=True),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("countries", postgresql.ARRAY(sa.String(length=10)), nullable=True),
        sa.Column("group_normalizado", sa.Text(), nullable=True),
        sa.Column("logo", sa.Text(), nullable=True),
        sa.Column("not_found", sa.Boolean(), server_default="false", nullable=True),
        sa.Column("retry_count", sa.Integer(), server_default="0", nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("last_sync_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["tmdb_id"], ["series_metadata.tmdb_id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uq_series_catalog_tmdb",
        "series_catalog",
        ["tmdb_id"],
        unique=True,
        postgresql_where=sa.text("tmdb_id IS NOT NULL"),
    )
    op.create_table(
        "watch_progress",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("content_id", sa.String(length=100), nullable=False),
        sa.Column("content_type", sa.String(length=20), nullable=False),
        sa.Column("position_ms", sa.BigInteger(), nullable=False),
        sa.Column("duration_ms", sa.BigInteger(), nullable=False),
        sa.Column("series_name", sa.String(length=255), nullable=True),
        sa.Column("season_number", sa.Integer(), nullable=True),
        sa.Column("episode_number", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("image_url", sa.String(), nullable=False),
        sa.Column("last_watched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_watched", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id",
            "content_id",
            "season_number",
            "episode_number",
            name="watch_progress_user_content_unique",
            postgresql_nulls_not_distinct=True,
        ),
    )
    op.create_table(
        "movie_streams",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("movie_id", sa.UUID(), nullable=False),
        sa.Column("country", sa.String(length=10), nullable=False),
        sa.Column("quality", sa.String(length=10), nullable=True),
        sa.Column("provider_id", sa.String(length=50), nullable=True),
        sa.Column("stream_url", sa.Text(), nullable=False),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("label", sa.Text(), nullable=True),
        sa.Column("numero", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["movie_id"], ["movies_catalog.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("movie_id", "provider_id", name="uq_movie_streams"),
    )
    op.create_table(
        "series_episodes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("catalog_id", sa.UUID(), nullable=False),
        sa.Column("season_number", sa.Integer(), nullable=False),
        sa.Column("episode_number", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("overview", sa.Text(), nullable=True),
        sa.Column("air_date", sa.Date(), nullable=True),
        sa.Column("still_path", sa.String(length=255), nullable=True),
        sa.Column("numero", sa.Integer(), nullable=True),
        sa.Column("title_en", sa.Text(), nullable=True),
        sa.Column("overview_en", sa.Text(), nullable=True),
        sa.Column("runtime", sa.Integer(), nullable=True),
        sa.Column("vote_average", sa.Float(), nullable=True),
        sa.Column("vote_count", sa.Integer(), nullable=True),
        sa.Column("episode_type", sa.String(length=50), nullable=True),
        sa.Column("tmdb_checked", sa.Boolean(), nullable=True),
        sa.Column("tmdb_not_found", sa.Boolean(), server_default="false", nullable=True),
        sa.Column("tmdb_retry_count", sa.Integer(), server_default="0", nullable=True),
        sa.Column("tmdb_last_error", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["catalog_id"], ["series_catalog.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("catalog_id", "season_number", "episode_number"),
    )
    op.create_table(
        "series_streams",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("episode_id", sa.UUID(), nullable=False),
        sa.Column("country", sa.String(length=10), nullable=False),
        sa.Column("quality", sa.String(length=10), nullable=True),
        sa.Column("provider_id", sa.String(length=50), nullable=True),
        sa.Column("stream_url", sa.Text(), nullable=False),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("label", sa.Text(), nullable=True),
        sa.Column("numero", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["episode_id"], ["series_episodes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("episode_id", "provider_id", name="uq_series_streams"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("series_streams")
    op.drop_table("series_episodes")
    op.drop_table("movie_streams")
    op.drop_table("watch_progress")
    op.drop_index(
        "uq_series_catalog_tmdb",
        table_name="series_catalog",
        postgresql_where=sa.text("tmdb_id IS NOT NULL"),
    )
    op.drop_table("series_catalog")
    op.drop_index(
        "uq_movies_catalog_tmdb",
        table_name="movies_catalog",
        postgresql_where=sa.text("tmdb_id IS NOT NULL"),
    )
    op.drop_table("movies_catalog")
    op.drop_table("channel_variants")
    op.drop_table("channel_favorites")
    op.drop_table("active_sessions")
    op.drop_table("users")
    op.drop_table("sync_metadata")
    op.drop_table("series_metadata")
    op.drop_index(
        "idx_failures_series",
        table_name="scraper_failures",
        postgresql_where=sa.text("series_key IS NOT NULL"),
    )
    op.drop_index(
        "idx_failures_provider",
        table_name="scraper_failures",
        postgresql_where=sa.text("provider_id IS NOT NULL"),
    )
    op.drop_table("scraper_failures")
    op.drop_table("replays")
    op.drop_table("movies_metadata")
    op.drop_table("config")
    op.drop_table("channels")
    op.drop_table("channel_mappings")
    op.drop_table("calendario")
    # ### end Alembic commands ###
